config/routes.rb
Rails.application.routes.draw do
  root 'map_pages#top'
  get 'railway_search/search', to: 'railway_search#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create] do
    member do
      get :activate
    end
  end
  get 'before_activate', to: 'users#before_activate'
  get  'new_activation', to: 'users#new_activation'
  post 'resend_activation', to: 'users#resend_activation'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[edit show update]
  
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  resources :posts, only: %i[index]
  resources :my_posts, only: %i[index]

  resources :crossings, only: %i[show] do
    collection do
      get :crossing_favorites
    end
    resources :posts, only: %i[new create show edit update destroy] do
      resources :comments, only: %i[create edit destroy]
      collection do
        get :favorites
      end
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :crossing_favorites, only: %i[index create destroy]  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @crossing = Crossing.find(params[:crossing_id])
    @post = Post.find(params[:post_id])
    current_user.favorite(@post)
  end

  def destroy
    @post = current_user.favorites.find(params[:id]).post
    @crossing = Crossing.find(params[:crossing_id])
    current_user.unfavorite(@post)
  end
end

app/views/favorites/_favorite.html.erb
<%= link_to favorites_path(post_id: post.id, crossing_id: crossing.crossing_id), id: "favorite-button-for-post-#{post.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-hand-thumbs-up"></i>
<% end%>

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(post) %>
  <%= render 'favorites/unfavorite', post: post, crossing: crossing %>
<% else %>
  <%= render 'favorites/favorite', post: post, crossing: crossing %>
<% end %>

app/views/favorites/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(post_id: post.id), crossing_id: crossing.crossing_id), id: "unfavorite-button-for-post-#{post.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-hand-thumbs-up-fill"></i>
<% end %>

app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.replace "favorite-button-for-post-#{@post.id}" do %>
  <%= render 'favorites/unfavorite', post: @post, crossing: @crossing %>
<% end %>

<%= turbo_stream.replace "favorite-count-#{@post.id}" do %>
  <div class="me-4 mx-2" id="unfavorite-count-<%= @post.id %>">
    <p>いいね <%= @post.favorites.count %></p>
  </div>
<% end %>

app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.replace "unfavorite-button-for-post-#{@post.id}" do %>
  <%= render 'favorites/favorite', post: @post, crossing: @crossing %>
<% end %>

<%= turbo_stream.replace "unfavorite-count-#{@post.id}" do %>
  <div class="me-4 mx-2" id="favorite-count-<%= @post.id %>">
    <p>いいね <%= @post.favorites.count %></p>
  </div>
<% end %>