config/routes.rb
Rails.application.routes.draw do
  root 'map_pages#top'
  get 'railway_search/search', to: 'railway_search#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create] do
    member do
      get :activate
    end
  end
  get 'before_activate', to: 'users#before_activate'
  get  'new_activation', to: 'users#new_activation'
  post 'resend_activation', to: 'users#resend_activation'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[edit show update]
  
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  resources :posts, only: %i[index]
  resources :my_posts, only: %i[index]

  resources :crossings, only: %i[show] do
    collection do
      get :crossing_favorites
    end
    resources :posts, only: %i[new create show edit update destroy] do
      resources :comments, only: %i[create edit destroy]
      collection do
        get :favorites
      end
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :crossing_favorites, only: %i[index create destroy]  
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <% if comment.user.avatar.present? %>
      <%= image_tag comment.user.avatar.url, class: 'rounded-circle', width: '30', height: '30' %>
    <% else %>
      <%= image_tag 'sample.jpg', class: 'rounded-circle', width: '30', height: '30' %>
    <% end %>
  </td>
  <td class="w-100">
    <h3 class="small"><%= comment.user.name %></h3>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <% if current_user && current_user.own?(comment) %>
    <td class="action text-nowrap align-middle">
      <%= link_to crossing_post_comment_path(comment.post.crossing_id, comment.post_id, comment), class: "delete-comment-link btn btn-outline-danger btn-sm rounded-pill py-0", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
        <i class="bi bi-trash-fill"></i>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-12">
    <%= form_with model: [crossing, post, comment], url: crossing_post_comments_path(crossing.crossing_id, post.id), local: false do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: "btn btn-warning rounded-pill shadow" %>
    <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, post: @comment.post, crossing: @comment.post.crossing %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, post: @comment.post, crossing: @comment.post.crossing %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" do %>
<% end %>