config/routes.rb
Rails.application.routes.draw do
  root 'map_pages#top'
  get 'railway_search/search', to: 'railway_search#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create] do
    member do
      get :activate
    end
  end
  get 'before_activate', to: 'users#before_activate'
  get  'new_activation', to: 'users#new_activation'
  post 'resend_activation', to: 'users#resend_activation'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[edit show update]
  
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  resources :posts, only: %i[index]
  resources :my_posts, only: %i[index]

  resources :crossings, only: %i[show] do
    collection do
      get :crossing_favorites
    end
    resources :posts, only: %i[new create show edit update destroy] do
      resources :comments, only: %i[create edit destroy]
      collection do
        get :favorites
      end
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :crossing_favorites, only: %i[index create destroy]  
end

app/views/shared/_account_page_side.html.erb
<div class="side-menu col-sm-12 col-md-4 col-lg-3">
  <div class="d-flex flex-column mt-3 text-secondary">
    <%= link_to 'プロフィール', profile_path, class: 'p-2 text-reset text-decoration-none' %>
    <%= link_to 'My投稿', my_posts_path, class: 'p-2 text-reset text-decoration-none' %>
    <%= link_to 'お気に入りフミキリ', crossing_favorites_path, class: 'p-2 text-reset text-decoration-none' %>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation bg-white navbar-light fixed-top shadow">
    <div class="container-fluid">
      <%= link_to '/', class: 'navbar-brand' do %>
        <%= image_tag '仮logo.png' %>
      <% end %>
      <button class="navbar-toggler" type="button" aria-label="Toggle navigation" id="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto main-nav align-items-center gap-2">
          <li class="nav-item">
            <%= link_to posts_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-file-post"></i>
              <span>投稿一覧</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-person-circle"></i>
              <span class="mb-0">ユーザー登録</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to login_path, class: "btn btn-warning rounded-pill shadow d-flex align-items-center gap-2" do %>
              <i class="bi bi-box-arrow-in-right"></i>
              <span>ログイン</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_before_login_root_header.html.erb
<header>
  <nav class='navbar navigation navbar-light fixed-top'>
    <div class="container-fluid">
      <div class="navbar-brand"></div>
      <div class='navbar-collapse'>
        <ul class='navbar-nav d-flex flex-row justify-content-end align-items-center gap-2'>
          <li class='nav-item'>
            <%= link_to posts_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-file-post"></i>
              <span class="mb-0">投稿一覧</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to new_user_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-person-circle"></i>
              <span class="mb-0">ユーザー登録</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to login_path, class: "btn btn-warning rounded-pill shadow d-flex align-items-center gap-2" do %>
              <i class="bi bi-box-arrow-in-right"></i>
              <span class="mb-0">ログイン</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_breadcrumbs.html.erb
<% case params.values_at(:controller, :action) %>
  <% when ['users', 'new'] %>
    <% breadcrumb :user_new %>

  <% when ['user_sessions', 'new'] %>
    <% breadcrumb :login %>

  <% when ['password_resets', 'new'] %>
    <% breadcrumb :password_reset %>

  <% when ['password_resets', 'edit'] %>
    <% breadcrumb :password_edit, @user %>

  <% when ['crossings', 'show'] %>
    <% breadcrumb :crossing, @crossing %>

  <% when ['posts', 'index'] %>
    <% breadcrumb :posts %>

  <% when ['posts', 'show'] %>
    <% breadcrumb :post, @post %>

  <% when ['posts', 'new'] %>
    <% breadcrumb :post_new, @crossing %>

  <% when ['posts', 'edit'] %>
    <% if params[:controller] == 'posts' && params[:action] == 'edit' && request.referer&.include?('/posts') %>
      <% breadcrumb :post_edit, @post, from: :posts %>
    <% else %>
      <% breadcrumb :post_edit, @post %>
    <% end %>

  <% when ['profiles', 'show'] %>
    <% breadcrumb :profile %>

  <% when ['profiles', 'edit'] %>
    <% breadcrumb :profile_edit %>

  <% when ['my_posts', 'index'] %>
    <% breadcrumb :my_posts %>

  <% when ['crossing_favorites', 'index'] %>
    <% breadcrumb :crossing_favorites %>
<% end %>

app/views/shared/_crossing_info.html.erb
<div class="mb-5">
  <div class="crossing-info text-center">
    <h4><%= crossing.crossing_name %></h4>
    <p class="mb-2">
      <%= link_to "#{crossing.latitude} / #{crossing.longitude}", "https://www.google.com/maps?q=#{crossing.latitude},#{crossing.longitude}", target: "_blank", rel: "noopener noreferrer" %>
    </p>
    <p class="mb-2"><%= crossing.city.prefecture.prefecture_name %></p>
    <p class="mb-2"><%= crossing.city.city_name %></p>
    <p class="mb-2"><%= crossing.linked_railways.first.railway_name %></p>
  </div>
  <div class="z-0 rounded" id="map" style="width: 100%; height: 350px;"></div>
</div>

<script>
  var map = L.map('map').setView([<%= crossing.latitude %>, <%= crossing.longitude %>], 13);

  L.tileLayer('https://tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey=abd7cf1c7d9d4b06b660b84796899098' , {
    attribution: '&copy; <a href="https://www.thunderforest.com/">Thunderforest</a> contributors'
  }).addTo(map);

  var marker = L.marker([<%= crossing.latitude %>, <%= crossing.longitude %>]).addTo(map).bindPopup('<%= link_to "詳細", crossing_path(crossing.crossing_id) %>').openPopup();

  map.zoomControl.setPosition("bottomright");
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="text-danger fw-semibold text-center w-50 mx-auto my-0 py-0 border-0">
    <ul class="list-unstyled d-flex flex-column align-items-center">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> d-flex align-items-center justify-content-center  flash-message shadow z-3">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-white shadow-lg'>
  <div class="container-fluid p-4">
    <div class='row d-flex justify-content-center align-items-center flex-column flex-md-row text-center text-md-start'>
      <div class="pages col-12 col-md-6 d-flex flex-column align-items-center text-info">
        <%= link_to '使い方', page_path('how_to_use'), class: 'p-2 text-reset text-decoration-none' %>
        <%= link_to '利用規約', page_path('service_terms'), class: 'p-1 text-reset text-decoration-none' %>
        <%= link_to 'プライバシーポリシー', page_path('privacy_policy'), class: 'p-1 text-reset text-decoration-none' %>
        <%= link_to 'お問い合わせ', new_contact_path, class: 'p-1 text-reset text-decoration-none' %>
      </div>
      <div class='copyright col-12 col-md-6 d-flex flex-column align-items-center text-secondary'>
        <%= link_to '/', class: 'navbar-brand' do %>
          <%= image_tag '仮logo.png' %>
        <% end %>
        <p class="mb-0">2025 fumikiri-map</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation bg-white navbar-light fixed-top shadow">
    <div class="container-fluid">
      <%= link_to '/', class: 'navbar-brand' do %>
        <%= image_tag '仮logo.png' %>
      <% end %>
      <button class="navbar-toggler" type="button" aria-label="Toggle navigation" id="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto main-nav align-items-center gap-2">
          <li class="nav-item">
            <%= link_to posts_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-file-post"></i>
              <span>投稿一覧</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to logout_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', data: { turbo_method: :delete } do %>
              <i class="bi bi-box-arrow-left"></i>
              <span>ログアウト</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to profile_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2' do %>
              <% if current_user.avatar.present? %>
                <%= image_tag current_user.avatar.url, class: 'rounded-circle', width: '25', height: '25' %>
              <% else %>
                <%= image_tag 'sample.jpg', class: 'rounded-circle', width: '25', height: '25' %>
              <% end %>
              <span><%= current_user.name %></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_post.html.erb
<div class="post-index my-4">
  <div class="row">
    <% posts.each do |post| %>
      <div class="col-12 col-md-6 col-lg-4 mb-3" id="post-id-<%= post.id %>">
        <div class="card shadow border-0" style="width: 100%;">
          <div class="ratio ratio-1x1">
            <%= image_tag post.crossing_image.url, class: "card-img-top w-100 h-100 object-fit-cover" %>
          </div>
          <div class="card-body">
            <%= link_to post.title, crossing_post_path(post.crossing_id, post.id), class: 'card-title text-decoration-none fw-semibold text-info' %>
            <p class="text-secondary"><i class="bi bi-calendar-event-fill me-2"></i><%= l post.created_at, format: :default %></p>
            <div class="d-flex">
              <p class="text-secondary"><i class="bi bi-person-fill me-2"></i><%= post.user.name %></p>
              <% if current_user && current_user.own?(post) %>
                <div class='ms-auto'>
                  <%= link_to edit_crossing_post_path(post.crossing_id, post.id), class: "btn btn-outline-info btn-sm rounded-pill py-0 px-2", id: "button-edit-#{post.id}" do %>
                    <i class="bi bi-pencil-fill"></i>
                  <% end %>
                  <%= link_to crossing_post_path(post.crossing_id, post.id), class: "btn btn-outline-danger btn-sm rounded-pill py-0 px-2", id: "button-delete-#{post.id}", data: { turbo_method: :delete, turbo_confirm: '投稿を削除しますか？' } do %>
                    <i class="bi bi-trash-fill"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <% post.tag_list.each do |tag| %>
              <span class="badge bg-dark-subtle mr-2 mb-2">
                <%= link_to "#{tag}", posts_path(tag_name: tag), class: 'text-decoration-none text-secondary' %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_root_header.html.erb
<header>
  <nav class='navbar navigation navbar-light fixed-top'>
    <div class="container-fluid">
      <div class="navbar-brand"></div>
      <div class='navbar-collapse'>
        <ul class='navbar-nav d-flex flex-row justify-content-end align-items-center gap-2'>
          <li class='nav-item'>
            <%= link_to posts_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', role: 'button' do %>
              <i class="bi bi-file-post"></i>
              <span class="mb-0">投稿一覧</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to logout_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2', data: { turbo_method: :delete } do %>
              <i class="bi bi-box-arrow-left"></i>
              <span class="mb-0">ログアウト</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to profile_path, class: 'btn btn-warning rounded-pill shadow d-flex align-items-center gap-2' do %>
              <% if current_user.avatar.present? %>
                <%= image_tag current_user.avatar.url, class: 'rounded-circle', width: '25', height: '25' %>
              <% else %>
                <%= image_tag 'sample.jpg', class: 'rounded-circle', width: '25', height: '25' %>
              <% end %>
              <span class="mb-0"><%= current_user.name %></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>