config/routes.rb
Rails.application.routes.draw do
  root 'map_pages#top'
  get 'railway_search/search', to: 'railway_search#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create] do
    member do
      get :activate
    end
  end
  get 'before_activate', to: 'users#before_activate'
  get  'new_activation', to: 'users#new_activation'
  post 'resend_activation', to: 'users#resend_activation'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[edit show update]
  
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  resources :posts, only: %i[index]
  resources :my_posts, only: %i[index]

  resources :crossings, only: %i[show] do
    collection do
      get :crossing_favorites
    end
    resources :posts, only: %i[new create show edit update destroy] do
      resources :comments, only: %i[create edit destroy]
      collection do
        get :favorites
      end
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :crossing_favorites, only: %i[index create destroy]  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password], params[:remember] == "1")

    if @user
      remember_me! if params[:remember_me] == "1"
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      @user = User.new
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    forget_me!
    logout
    redirect_to root_path, status: :see_other, success: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'shared/breadcrumbs' %>
<div class="container pt-5">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto">
      <h2 class="mb-4">ログイン</h2>
      <%= form_with url: login_path do |f| %>
      <%= render 'shared/error_messages', object: @user %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control border-0 shadow" %>
        </div>
        <div class="mb-4">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control border-0 shadow" %>
        </div>
        <div class="d-flex align-items-center justify-content-center mb-2">
          <%= f.label :remember_me, class:'me-2' %>
          <%= f.check_box :remember_me, {}, "1", "0" %>
        </div>
        <div class="d-flex justify-content-center">
          <%= f.submit "ログイン", class: "btn btn-warning rounded-pill shadow px-4", value: "ログイン", id: "login-btn" %>
        </div>
      <% end %>
      <div class="d-flex justify-content-center mt-5">
        <%= link_to auth_at_provider_path(:google), class: 'btn btn-primary rounded-pill shadow d-flex align-items-center px-4 gap-2', data: { turbo: false } do %>
          <i class="bi bi-google text-light"></i>
          <p class="text-light">Login with Google</p>
        <% end %>
      </div>
      <div class='text-center mt-4'>
        <%= link_to 'アカウント登録', new_user_path, class: 'btn btn-warning rounded-pill shadow mb-3 px-4' %>
        <%= link_to t('.password_forget'), new_password_reset_path, class: 'btn btn-warning rounded-pill shadow mb-3 px-4' %>
        <%= link_to '認証メール再送', new_activation_path, class: 'btn btn-warning rounded-pill shadow mb-3 px-4' %>
      </div>
    </div>
  </div>
</div>